export const TIERS = {
  free: {
    id: "free",
    name: "Free",
    tagline: "Start exploring markets",
    monthlyPrice: 0,
    yearlyPrice: 0,
    yearlySavings: null,
    color: "#6b7a99",
    borderColor: "#1a2235",
    features: [
      { label: "Basic crypto & equities data",              locked: false },
      { label: "Macro Calendar (view only)",                locked: false },
      { label: "Signals delayed 30 min — direction only",  locked: false },
      { label: "Real-time signals with entry, SL & TP",    locked: true,  note: "Pro" },
      { label: "AI confidence breakdown per signal",        locked: true,  note: "Pro" },
      { label: "Signal history & PnL records",             locked: true,  note: "Pro" },
      { label: "AI Chat · Morning Brief · Price Alerts",   locked: true,  note: "Pro" },
      { label: "SEC Insider Flow · AI Quant Engine",       locked: true,  note: "Elite only" },
    ],
  },
  pro: {
    id: "pro",
    name: "CLVR Pro",
    tagline: "The Retail Advantage",
    monthlyPrice: 29.99,
    yearlyPrice: 299.00,
    yearlySavings: 60,
    stripePriceMonthly: "price_pro_monthly",
    stripePriceYearly:  "price_pro_yearly",
    color: "#d4af37",
    borderColor: "rgba(212,175,55,0.45)",
    badge: null,
    features: [
      { label: "Real-time signals — zero delay",                      locked: false },
      { label: "Full entry, stop-loss & take-profit targets",         locked: false },
      { label: "AI confidence breakdown per signal",                  locked: false },
      { label: "Full signal history + PnL records",                   locked: false },
      { label: "CLVR AI Market Chat · 30 req/day",                    locked: false },
      { label: "Morning Brief · Full Macro Calendar",                  locked: false },
      { label: "Custom price alerts & push notifications",            locked: false },
      { label: "AI Quant Engine",                                     locked: true,  note: "Elite only" },
      { label: "SEC Insider Flow · Basket Analysis",                  locked: true,  note: "Elite only" },
    ],
  },
  elite: {
    id: "elite",
    name: "CLVR Elite",
    tagline: "The Institutional Edge",
    monthlyPrice: 129.00,
    yearlyPrice: 1199.00,
    yearlySavings: 349,
    stripePriceMonthly: "price_elite_monthly",
    stripePriceYearly:  "price_elite_yearly",
    color: "#00e5ff",
    borderColor: "rgba(0,229,255,0.55)",
    badge: "RECOMMENDED",
    features: [
      { label: "All Pro markets + Forex & Commodities", locked: false, elite: true },
      { label: "QuantBrain AI · Unlimited requests",    locked: false, elite: true },
      { label: "AI Quant Engine — full access",         locked: false, elite: true },
      { label: "SEC Insider Flow · Whale tracking",     locked: false, elite: true, tag: "ELITE EXCLUSIVE" },
      { label: "Basket Analysis (3+ assets)",           locked: false, elite: true, tag: "ELITE EXCLUSIVE" },
      { label: "Squawk Box — Live Signal Announcer",    locked: false, elite: true, tag: "ELITE EXCLUSIVE" },
      { label: "Political Alpha · Deep news correlation",locked: false, elite: true, tag: "ELITE EXCLUSIVE" },
      { label: "Custom SMS & browser price alerts",     locked: false, elite: true },
      { label: "Funding rate flip alerts",              locked: false, elite: true },
    ],
  },
};

export const TIER_ORDER = ["free", "pro", "elite"];

export function canAccess(userTier, requiredTier) {
  return TIER_ORDER.indexOf(userTier) >= TIER_ORDER.indexOf(requiredTier);
}
